Modify paired-end dispatcher logic
maxrossi91/moni-align pull request #32
Opened 2024-03-28 19:01 UTC by rvarki

This modifies the paired-end dispatcher logic. Instead of storing the partial alignments of the learning reads until learning is complete, we instead should not store them and redo the full alignment for these reads after learning is complete. Of course,  we have to do some redundant alignment work as a result, but since it is only for a small amount of reads (~1000) it is worth it for the memory savings. This reduces the peak memory significantly from my testings (90+% when redoing the chr21 experiments).

2024-03-28 19:04 UTC, rvarki commented
I profiled the memory usage each time the align function was called with malloc_count using a single thread and found that the memory was only climbing during the learning process.

2024-04-17 23:51 UTC, maxrossi91 requested changes
Remove the commented code. I think it is ok to change the behavior. It may need to run twice on some reads, but it might be acceptable.

2024-04-17 23:51 UTC, maxrossi91 commented on include/aligner/align_reads_dispatcher.hpp
> +          // alignments.clear(); alignments.shrink_to_fit();
Please, remove the commented lines.

2024-04-24 17:36 UTC, rvarki commented
Removed commented out code.

2024-05-03 16:40 UTC, merged